### ISSUE TITLE
System.ObjectDisposedException: The semaphore has been disposed.

### ISSUE THREAD

**Issue by aKzenT** [JeringTech/Javascript.NodeJS#152]
I was doing some testing of my website under heavy load and encountered the following exception:

```
info: Jering.Javascript.NodeJS.HttpNodeJSService[0]
      Connected to NodeJS process: -1.
info: Jering.Javascript.NodeJS.HttpNodeJSService[0]
      Connected to NodeJS process: -1.
Unhandled exception. System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.OutputReceivedHandler(String message, DisposeTrackingSemaphoreSlim semaphoreSlim)
   at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.<>c__DisplayClass50_0.<CreateAndSetUpProcess>b__1(String message)
   at Jering.Javascript.NodeJS.NodeJSProcess.OutputThreadStart(Object arg)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

As I said it was under heavy load with many concurrent requests, so it might be some concurrency problem. Unfortunately I don't have more logs than that.

I was using the latest beta version of the library.

Thank you for your help!

**Comment by JeremyTCD** [comment]
Hey, apologies for the slow response.  

Thanks for the stack log. It seems the Node.js process is still sending messages (`OutputReceivedHandler`) after it has been disposed. This is likely due a change I made in the beta version where `NodeJSProcess.Dispose()` no longer blocked till the process exited.  

I've added back the wait for exit logic. In .Net 5.0 and above, the wait is now async.

I'll be publishing a new 7.0.0 beta version later today with the changes.  

Feel free to open a new issue if you encounter any other problems!
